using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace LivingDiorama.EditorTools
{
    /// <summary>
    /// Applies import settings to the interface art generated by
    /// Tools/recraft_ui_pipeline.py.
    ///
    /// The pipeline writes the PNGs and a small manifest saying which of them are
    /// nine-sliced and by how much; this turns that into TextureImporter settings.
    /// Doing it here rather than by writing .meta files from Python is deliberate: a
    /// .meta carries the asset guid, and a guid collision breaks every reference to
    /// the file in a way that is tedious to unpick. A wrong slice border is a
    /// one-line fix.
    ///
    /// Safe to run repeatedly; it only reimports what it actually changed.
    /// </summary>
    public static class UiArtImporter
    {
        const string ArtDir = "Assets/Resources/UI/Art";
        const string Manifest = ArtDir + "/_import.json";

        [Serializable]
        sealed class SpriteEntry
        {
            public string key;
            public int[] border;    // left, bottom, right, top -- null when not sliced
            public int maxSize;
        }

        [Serializable]
        sealed class ManifestFile
        {
            public SpriteEntry[] sprites;
        }

        [MenuItem("Living Diorama/Import UI Art", priority = 4)]
        public static void ImportAll()
        {
            if (!File.Exists(Manifest))
            {
                Debug.LogWarning($"[UiArtImporter] no manifest at '{Manifest}'. " +
                                 "Run Tools/recraft_ui_pipeline.py generate first.");
                return;
            }

            var manifest = JsonUtility.FromJson<ManifestFile>(File.ReadAllText(Manifest));
            if (manifest?.sprites == null)
            {
                Debug.LogError($"[UiArtImporter] could not read '{Manifest}'");
                return;
            }

            int changed = 0;

            foreach (SpriteEntry entry in manifest.sprites)
            {
                string path = $"{ArtDir}/{entry.key}.png";

                if (AssetImporter.GetAtPath(path) is not TextureImporter importer)
                {
                    Debug.LogWarning($"[UiArtImporter] {entry.key}: no texture at '{path}'");
                    continue;
                }

                if (Configure(importer, entry))
                {
                    importer.SaveAndReimport();
                    changed++;
                }
            }

            AssetDatabase.Refresh();
            Debug.Log($"[UiArtImporter] {changed} of {manifest.sprites.Length} sprite(s) reimported");
        }

        /// <summary>Returns true when anything actually needed changing.</summary>
        static bool Configure(TextureImporter importer, SpriteEntry entry)
        {
            Vector4 border = entry.border is { Length: 4 }
                ? new Vector4(entry.border[0], entry.border[1], entry.border[2], entry.border[3])
                : Vector4.zero;

            var settings = new TextureImporterSettings();
            importer.ReadTextureSettings(settings);

            bool dirty =
                importer.textureType != TextureImporterType.Sprite ||
                importer.spriteImportMode != SpriteImportMode.Single ||
                importer.spriteBorder != border ||
                importer.mipmapEnabled ||
                importer.wrapMode != TextureWrapMode.Clamp ||
                importer.filterMode != FilterMode.Bilinear ||
                !importer.alphaIsTransparency ||
                importer.maxTextureSize != entry.maxSize ||
                settings.spriteMeshType != SpriteMeshType.FullRect;

            if (!dirty) return false;

            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.spriteBorder = border;

            // Full rect, not tight. With the default, Unity trims the transparent
            // margin off the mesh and the slice insets no longer line up with the art
            // -- which looks like the ornament has slipped, not like a setting is
            // wrong, and is the fiddliest of these to diagnose after the fact.
            settings.spriteMeshType = SpriteMeshType.FullRect;
            settings.spriteBorder = border;
            importer.SetTextureSettings(settings);

            // Interface textures are never minified, so mipmaps are pure waste; and
            // clamped bilinear is what stops a nine-slice bleeding its opposite edge
            // into itself.
            importer.mipmapEnabled = false;
            importer.wrapMode = TextureWrapMode.Clamp;
            importer.filterMode = FilterMode.Bilinear;
            importer.alphaIsTransparency = true;
            importer.maxTextureSize = entry.maxSize;

            importer.SetPlatformTextureSettings(new TextureImporterPlatformSettings
            {
                name = "Android",
                overridden = true,
                maxTextureSize = entry.maxSize,
                format = TextureImporterFormat.ASTC_6x6,
                textureCompression = TextureImporterCompression.Compressed,
            });

            return true;
        }
    }
}
